export { VALIDATION } from "./validation";

export const DAY_NAMES = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
] as const;

export const ErrorCode = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_PRIVACY_NOT_ACCEPTED: "AUTH_PRIVACY_NOT_ACCEPTED",
  AUTH_EMAIL_CONFLICT: "AUTH_EMAIL_CONFLICT",
  AUTH_ACCESS_DENIED: "AUTH_ACCESS_DENIED",
  AUTH_REFRESH_TOKEN_REQUIRED: "AUTH_REFRESH_TOKEN_REQUIRED",
  GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
  GROUP_INVALID_INVITE_CODE: "GROUP_INVALID_INVITE_CODE",
  GROUP_ALREADY_MEMBER: "GROUP_ALREADY_MEMBER",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  MEMBER_ADMIN_REQUIRED: "MEMBER_ADMIN_REQUIRED",
  MEMBER_SOLE_ADMIN_REMOVE: "MEMBER_SOLE_ADMIN_REMOVE",
  MEMBER_SOLE_ADMIN_DEMOTE: "MEMBER_SOLE_ADMIN_DEMOTE",
  INVITATION_ADMIN_ONLY: "INVITATION_ADMIN_ONLY",
  INVITATION_ALREADY_MEMBER: "INVITATION_ALREADY_MEMBER",
  INVITATION_ALREADY_PENDING: "INVITATION_ALREADY_PENDING",
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  INVITATION_NOT_OWNER: "INVITATION_NOT_OWNER",
  INVITATION_ALREADY_RESPONDED: "INVITATION_ALREADY_RESPONDED",
  FORBIDDEN_NOT_MEMBER: "FORBIDDEN_NOT_MEMBER",
  FORBIDDEN_NOT_ADMIN: "FORBIDDEN_NOT_ADMIN",
  FORBIDDEN_NOT_EDITOR: "FORBIDDEN_NOT_EDITOR",
  FORBIDDEN_MISSING_CONTEXT: "FORBIDDEN_MISSING_CONTEXT",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  GROUP_DELETE_FAILED: "GROUP_DELETE_FAILED",
  LESSON_CREATE_FAILED: "LESSON_CREATE_FAILED",
  LESSON_NOT_FOUND: "LESSON_NOT_FOUND",
  LESSON_UPDATE_FAILED: "LESSON_UPDATE_FAILED",
  LESSON_NOT_OWNER: "LESSON_NOT_OWNER",
  LESSON_NOT_EDITABLE: "LESSON_NOT_EDITABLE",
  LESSON_SUBMIT_FAILED: "LESSON_SUBMIT_FAILED",
  LESSON_INVALID_STATUS_FOR_SUBMIT: "LESSON_INVALID_STATUS_FOR_SUBMIT",
  LESSON_DELETE_FAILED: "LESSON_DELETE_FAILED",
  LESSON_DELETE_NOT_ALLOWED: "LESSON_DELETE_NOT_ALLOWED",
  LESSON_APPROVE_FAILED: "LESSON_APPROVE_FAILED",
  LESSON_REJECT_FAILED: "LESSON_REJECT_FAILED",
  LESSON_NOT_IN_REVIEW: "LESSON_NOT_IN_REVIEW",
  FLASHCARD_DECK_NOT_FOUND: "FLASHCARD_DECK_NOT_FOUND",
  FLASHCARD_CARD_NOT_FOUND: "FLASHCARD_CARD_NOT_FOUND",
  FLASHCARD_CREATE_FAILED: "FLASHCARD_CREATE_FAILED",
  FLASHCARD_DELETE_FAILED: "FLASHCARD_DELETE_FAILED",
  FLASHCARD_IMPORT_FAILED: "FLASHCARD_IMPORT_FAILED",
  FLASHCARD_EMPTY_DECK: "FLASHCARD_EMPTY_DECK",
  REVIEW_COMMENT_CREATE_FAILED: "REVIEW_COMMENT_CREATE_FAILED",
  REVIEW_COMMENT_NOT_FOUND: "REVIEW_COMMENT_NOT_FOUND",
  REVIEW_COMMENT_BODY_REQUIRED: "REVIEW_COMMENT_BODY_REQUIRED",
  REVIEW_COMMENT_DELETE_FAILED: "REVIEW_COMMENT_DELETE_FAILED",
  FORBIDDEN_NOT_COMMENT_OWNER: "FORBIDDEN_NOT_COMMENT_OWNER",
  LEARNING_PATH_ITEM_NOT_FOUND: "LEARNING_PATH_ITEM_NOT_FOUND",
  LEARNING_PATH_ITEM_EXISTS: "LEARNING_PATH_ITEM_EXISTS",
  REACTION_FAILED: "REACTION_FAILED",
  PROGRESS_UPDATE_FAILED: "PROGRESS_UPDATE_FAILED",
  LESSON_ALREADY_SOFT_DELETED: "LESSON_ALREADY_SOFT_DELETED",
} as const;

export const GROUP_ROLES = {
  ADMIN: "admin",
  EDITOR: "editor",
  MEMBER: "member",
} as const;

export type MemberRole = (typeof GROUP_ROLES)[keyof typeof GROUP_ROLES];

export const INVITATION_STATUS = {
  PENDING: "pending",
  ACCEPTED: "accepted",
  DECLINED: "declined",
} as const;

export const LESSON_STATUS = {
  DRAFT: "draft",
  REVIEW: "review",
  PUBLISHED: "published",
  REJECTED: "rejected",
  DELETED: "deleted",
} as const;

export type LessonStatus = (typeof LESSON_STATUS)[keyof typeof LESSON_STATUS];

export const FLASHCARD_DECK_STATUS = {
  DRAFT: "draft",
  PUBLISHED: "published",
} as const;

export type FlashcardDeckStatus = (typeof FLASHCARD_DECK_STATUS)[keyof typeof FLASHCARD_DECK_STATUS];

export const ReactionType = {
  THUMBS_UP: "thumbs_up",
  THUMBS_DOWN: "thumbs_down",
  HEART: "heart",
  LIGHTBULB: "lightbulb",
} as const;

export type ReactionType = (typeof ReactionType)[keyof typeof ReactionType];

export const AliveTextInteractionType = {
  REVEAL: "reveal",
} as const;

export type AliveTextInteractionType = (typeof AliveTextInteractionType)[keyof typeof AliveTextInteractionType];
