export { VALIDATION } from "./validation";

export const DAY_NAMES = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
] as const;

export const ErrorCode = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_PRIVACY_NOT_ACCEPTED: "AUTH_PRIVACY_NOT_ACCEPTED",
  AUTH_EMAIL_CONFLICT: "AUTH_EMAIL_CONFLICT",
  AUTH_ACCESS_DENIED: "AUTH_ACCESS_DENIED",
  AUTH_REFRESH_TOKEN_REQUIRED: "AUTH_REFRESH_TOKEN_REQUIRED",
  GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
  GROUP_INVALID_INVITE_CODE: "GROUP_INVALID_INVITE_CODE",
  GROUP_ALREADY_MEMBER: "GROUP_ALREADY_MEMBER",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  MEMBER_ADMIN_REQUIRED: "MEMBER_ADMIN_REQUIRED",
  MEMBER_SOLE_ADMIN_REMOVE: "MEMBER_SOLE_ADMIN_REMOVE",
  MEMBER_SOLE_ADMIN_DEMOTE: "MEMBER_SOLE_ADMIN_DEMOTE",
  INVITATION_ADMIN_ONLY: "INVITATION_ADMIN_ONLY",
  INVITATION_ALREADY_MEMBER: "INVITATION_ALREADY_MEMBER",
  INVITATION_ALREADY_PENDING: "INVITATION_ALREADY_PENDING",
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  INVITATION_NOT_OWNER: "INVITATION_NOT_OWNER",
  INVITATION_ALREADY_RESPONDED: "INVITATION_ALREADY_RESPONDED",
  FORBIDDEN_NOT_MEMBER: "FORBIDDEN_NOT_MEMBER",
  FORBIDDEN_NOT_ADMIN: "FORBIDDEN_NOT_ADMIN",
  FORBIDDEN_MISSING_CONTEXT: "FORBIDDEN_MISSING_CONTEXT",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  GROUP_DELETE_FAILED: "GROUP_DELETE_FAILED",
} as const;

export const GROUP_ROLES = {
  ADMIN: "admin",
  EDITOR: "editor",
  MEMBER: "member",
} as const;

export type MemberRole = (typeof GROUP_ROLES)[keyof typeof GROUP_ROLES];

export const INVITATION_STATUS = {
  PENDING: "pending",
  ACCEPTED: "accepted",
  DECLINED: "declined",
} as const;

export const LESSON_STATUS = {
  DRAFT: "draft",
  REVIEW: "review",
  PUBLISHED: "published",
} as const;
