export const VALIDATION = {
  PASSWORD_MIN: 6,
  PASSWORD_MAX: 128,

  DISPLAY_NAME_MIN: 1,
  DISPLAY_NAME_MAX: 50,

  GROUP_NAME_MIN: 1,
  GROUP_NAME_MAX: 100,
  GROUP_DESCRIPTION_MAX: 500,

  PROFILE_FIELD_MAX: 120,
  AGE_MIN: 5,
  AGE_MAX: 120,

  DEADLINE_DAY_MIN: 0,
  DEADLINE_DAY_MAX: 6,
  DEADLINE_TIME_REGEX: /^([01]\d|2[0-3]):[0-5]\d$/,

  INVITE_CODE_LENGTH: 8,
  INVITE_CODE_CHARSET: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",

  LESSON_TITLE_MIN: 1,
  LESSON_TITLE_MAX: 200,
  LESSON_CONTENT_MARKDOWN_MAX: 500000,

  AVATAR_MAX_SIZE_BYTES: 2 * 1024 * 1024,
  AVATAR_ALLOWED_MIME_TYPES: ["image/jpeg", "image/png"],
} as const;
